### ISSUE TITLE
Is this support RS97-Plus

### ISSUE THREAD

**Issue by asypost** [steward-fu/rs97#1]
Hi,I am wondering is this source code support RS97-Plus which has joystick.

**Comment by steward-fu** [comment]
Hi,
Yes, it doesn't support your favorite device(RS97+).
This repo is just for source reference only and used in very early RetroGame(RS97) device.
So far, it is orphan.

**Comment by asypost** [comment]
So is there any other way to build Linux from scratch for RS-97 Plus?

**Comment by steward-fu** [comment]
Kernel: https://github.com/rs-97-cfw/rs97-linux-kernel-NoNDA
Buildroot: https://github.com/rs-97-cfw/buildroot

**Comment by asypost** [comment]
@steward-fu Thanks a lot!
